apiVersion: v1
kind: Namespace
metadata:
  name: pred8tor
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pred8tor
  namespace: pred8tor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pred8tor
  template:
    metadata:
      labels:
        app: pred8tor
    spec:
      serviceAccountName: pred8tor
      containers:
      - name: pred8tor
        image: pavelzagalsky/pred8tor:1.0.0
        imagePullPolicy: Always
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pred8tor
  namespace: pred8tor
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pred8tor
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pred8tor
subjects:
- kind: ServiceAccount
  name: pred8tor
  namespace: pred8tor
roleRef:
  kind: ClusterRole
  name: pred8tor
  apiGroup: rbac.authorization.k8s.io
