apiVersion: v1
kind: Namespace
metadata:
  name: pred8tor
  labels:
    expiration_time: "1706263086"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: pred8tor
  labels:
    app: nginx
    expiration_time: "1706263086"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        expiration_time: "1706263086"
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: pred8tor
  labels:
    expiration_time: "1706263086"
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
