name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        ls
        pwd
        docker build . --file app/Dockerfile --tag pavelzagalsky/pred8tor:$(date +%s)
